### ISSUE TITLE
does it work with Jetson Jetpack 4.5.1?

### ISSUE THREAD

**Issue by AndreV84** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#18]
Hi, Thank you for your contribution. 
Could you advise where to start given we are interested in use of Deepstream integrattion with the most recent Jetpack 4.5.1 release of the Jetson OS , please?

**Comment by toolboc** [comment]
@AndreV84, there is no reason why it should not, due to bandwidth constraints I have not tested personally but would say the odds are highly in your favor that it will "just work" ^TM.  Let us know if you get this up and running and we'll close out the issue.

**Comment by AndreV84** [comment]
Hi @toolboc Is there any chance to run the thing without use of the visual code at all?
I installed it both on Jetson / Host x88_64 PC.
It can not execute Select IoT Hub from both devices , as the VSCode is argumenting that it can not find subscription. However there is one that I am using to create IoT hub, device, storage etc.
moreover. Can we not use the visual code  as it fails discovering one of the active subscription at the account? can we use some other deployment approach than the vscode?

**Comment by AndreV84** [comment]
failing deployment with this
```
[Edge] Deployment failed. ArgumentError: Property or Tag name has invalid characters. Error in Property/Tag $LOCAL_STORAGE_ACCOUNT_NAME. Must not contain Control Characters, '.', '$', '#', or ' '.
```
the .env file has entries:
```
CONTAINER_REGISTRY_NAME=
LOCAL_STORAGE_ACCOUNT_KEY=3CuWSiDUYNDTT9UeL7OhLQ==
LOCAL_STORAGE_ACCOUNT_NAME=123
DESTINATION_STORAGE_NAME=camerataggingmodulecloud
CLOUD_STORAGE_CONNECTION_STRING=

**Comment by AndreV84** [comment]
```
NVIDIADeepStreamSDK
IoT Edge Custom Module
Yes
Yes
failed
255
```
this one seems getting failed

**Comment by AndreV84** [comment]
what is the command it starts it with? how do I manually start it? how to troubleshoot?
```
3864f670238f        nvcr.io/nvidia/deepstream-l4t:5.0-20.07-iot                                 "/usr/bin/deepstream…"    4 hours ago         Exited (255) 10 seconds ago                                                                          NVIDIADeepStreamSDK

**Comment by AndreV84** [comment]
failing in section 2.6 using this instruction https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/docs/Module%202%20-%20Configure%20and%20Deploy%20Intelligent%20Video%20Analytics%20to%20IoT%20Edge%20Runtime%20on%20NVIDIA%20Jetson.md

**Comment by AndreV84** [comment]
```
root@agx:/opt/nvidia/deepstream/deepstream-5.0# /usr/bin/deepstream-test5-app -c /data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/DSConfig-CustomVisionAI.txt

 *** DeepStream: Launched RTSP Streaming at rtsp://localhost:8554/ds-test ***


(deepstream-test5-app:20): GLib-CRITICAL **: 18:54:21.244: g_strrstr: assertion 'haystack != NULL' failed
Error: Time:Wed Mar 31 18:54:21 2021 File:/home/nvidia/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:retrieve_edge_environment_variabes Line:177 Environment IOTEDGE_AUTHSCHEME not set
Error: Time:Wed Mar 31 18:54:21 2021 File:/home/nvidia/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromEnvironment Line:1186 retrieve_edge_environment_variabes failed
Error: Time:Wed Mar 31 18:54:21 2021 File:/home/nvidia/azure/azure-iot-sdk-c/iothub_client/src/iothub_client_core.c Func:create_iothub_instance Line:924 Failure creating iothub handle
ERROR: iotHubModuleClientHandle is NULL! connect failed
** ERROR: <main:1451>: Failed to set pipeline to PAUSED
Quitting
ERROR from sink_sub_bin_sink2: Could not configure supporting library.
Debug info: /dvs/git/dirty/git-master_linux/deepstream/sdk/src/gst-plugins/gst-nvmsgbroker/gstnvmsgbroker.c(388): legacy_gst_nvmsgbroker_start (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
unable to connect to broker library
ERROR from sink_sub_bin_sink2: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Debug info: gstbasesink.c(5265): gst_base_sink_change_state (): /GstPipeline:pipeline/GstBin:sink_sub_bin2/GstNvMsgBroker:sink_sub_bin_sink2:
Failed to start

```
that if I try to run the contrainer with the config file separately manually

**Comment by AndreV84** [comment]
I will try to do the steps on one more jetson - anothre board also flashed with Jetpack 4.5.1

**Comment by AndreV84** [comment]
at nx [ it has no display at all so after first run I disabled the GL sink to fake sink
but the error seems the same as at AGX
```
 iotedge logs NVIDIADeepStreamSDK
nvbuf_utils: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
nvbuf_utils: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
2021-04-01 11:42:13.554186: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
2021-04-01 11:42:14.602195: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
No EGL Display 
nvbufsurftransform: Could not get EGL display connection
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by toolboc** [comment]
The error indicating "Could not get EGL display connection" implies that you may not be exposing the appropriate v4l device to the container, this is accomplished in the IoT Edge docker create options here: https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/issues/18

Have you exposed the X11 socket and proper V4L path to the container and also set the appropriate xhost options?  See: https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/docs/Module%202%20-%20Configure%20and%20Deploy%20Intelligent%20Video%20Analytics%20to%20IoT%20Edge%20Runtime%20on%20NVIDIA%20Jetson.md#module-23--prepare-the-jetson-device-to-use-the-intelligent-video-analytics-sample-configurations

From what I can tell, you are running the DeepStream application on the host as a direct docker container without any connection to Azure IoT Edge and are thus going down a different series of steps from those mentioned in the Module sections.

**Comment by AndreV84** [comment]
@toolboc 
Thank you for following up
I tried running at local jetson with display conncted, but also without display conencted at another Jetson.
In my case with 20 or so attemps to run theapp it did not work at neither of the two devices.
It does't work without display connected at all, doesn't it?
The requirement of the display seems might be due to GLSink in the DeepStream config file. But the display doesn't cause termination of deepstream execution typically. Moreover, I I tried to switch the configuration to Fake sink/ Filesink from GLSink in efforts to troubleshoot it. However, I noticed that log files only reflect entries from first run of the container. From further running or restarting there are no more enrties in the log file added.
How to run the app so that deepstream gets running?
Have you had a chance to implement it with Deepstream 5.1? with Jetpack 4.5.1? With both? With neither of the two?
Is ther any way to get the thing running given I have two jetsons - one with Display also one without a display at all? How to exclude the display error if running the application at device that has the display, but excluding it to avoid the error at all?

**Comment by toolboc** [comment]
@AndreV84, 

I have had the chance to implement using DeepStream 5.1 and Jetpack 4.5.1 without issue (although this was using an in-place upgrade of Jetpack which is now possible via Debian based package updates).

One way that you could mitigate the issue possibly being related to a connected display is to only output results to an RTSP sink and connect to that for visual results.

**Comment by AndreV84** [comment]
How to make it work?
Does it require to re-deploy from VSCode?
OrI just run the restart docker command for DeepStream container after editing with
```
 nano /data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/DSConfig-CustomVisionAI.txt
```
here is sink section I put sink to 5 [rtsp] but I also tried other options
then
```
docker restart NVIDIADeepStreamSDK
```
The output is
```
iotedge logs NVIDIADeepStreamSDK
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by AndreV84** [comment]
I do not need visual output at this point but just to get the service running with Azure Iot.
even with Fakesink -sink0=1
```
 iotedge logs NVIDIADeepStreamSDK
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by AndreV84** [comment]
how to overcome this?
```
iotedge logs NVIDIADeepStreamSDK
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by AndreV84** [comment]
@toolboc with sink 0 =1 Fakesink the error is
```
 iotedge logs NVIDIADeepStreamSDK
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

```
with other values for sink in the file errors differ e.g.
with other sink combinations the errors differ but it won't work e.g.
```
iotedge logs NVIDIADeepStreamSDK
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed
** ERROR: <create_multi_source_bin:1057>: Failed to create element 'src_bin_muxer'
** ERROR: <create_multi_source_bin:1132>: create_multi_source_bin failed
** ERROR: <create_pipeline:1296>: create_pipeline failed
** ERROR: <main:1419>: Failed to create pipeline
Quitting
App run failed

**Comment by toolboc** [comment]
@AndreV84,

Any chance you can post the full contents of your DeepStream configuration file and associated IoT Edge Deployment Manfiest (with any username / passwords redacted)?

**Comment by AndreV84** [comment]
@toolboc 
[DSConfig-CustomVisionAI.txt](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/files/6267859/DSConfig-CustomVisionAI.txt)

[deployment.arm64v8_redacted.json.txt](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/files/6267867/deployment.arm64v8_redacted.json.txt)
the config file is located at /data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/DSConfig-CustomVisionAI.txt

the deployemnt manifest is generated by Vscode - tried from Jetson, also from x86_64
sometimes the deployment manifest also appears at Azure interface sometimes it doesnt regardless successfull status message at vscode after deploying it to device

**Comment by toolboc** [comment]
@AndreV84,

Take a look at this [potential resolution](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/issues/14#issuecomment-760555037), it is possible that you are setting an incorrect value for DISPLAY (in your deployment template this is set to '1').   This error likely has nothing to do with JetPack version and more likely to do with the X11 configuration on your device.

**Comment by AndreV84** [comment]
@toolboc Thank you for your response.
Yes, but I process attempts/ trials in batch like 10-12 configurations one after one after them failing
right after I tried with DISPALY 1. I also tried editing the 1 value in the vscode to 0 then pressed - deploy top sinbgle device. It did not change anything
I also tried disabling / changing every of the three sink\s in the Deepstream Configuration file.
Last day efforts did reflect all statuses OK but for Deepsteam 255 at Azure Web page. Moreover, this time there was no deployment manifest listed at Azure interface that was previously listed there.
Any ideas? But for the Display? How to exclude the Display at all but for editing the Deepstream config file? So that no display would be required for the Deepstream to repurt the OK status in Azure web page?

**Comment by AndreV84** [comment]
@toolboc could you confirm if the whole thing does work with disconnected display, please? given in the DeepStream config file eGL sink is disabled in favour of fakesink or just disabled?

**Comment by toolboc** [comment]
You should be able to isolate the issue by modifying the [DISPLAY env var name](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/issues/14#issuecomment-760555037)  to something like DISPLAY_PLACEHOLDER, which should force DeepStream to be unable to attempt to connect to any display, in addition to disabling or setting local output to a FakeSink.  

I've validated that the workload will work as expected when using FakeSink or disabling Source 0, in either case the output is as expected:

```
paul@jetson-xaviernx-00:~$ docker logs -f NVIDIADeepStreamSDK
2021-04-07 17:31:01.249303: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2

 *** DeepStream: Launched RTSP Streaming at rtsp://localhost:8554/ds-test ***


(deepstream-test5-app:1): GLib-CRITICAL **: 17:31:01.932: g_strrstr: assertion 'haystack != NULL' failed
0:00:07.132895324     1     0x3bea4d00 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::deserializeEngineAndBackend() <nvdsinfer_context_impl.cpp:1701> [UID = 1]: deserialized trt engine from :/data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/../../CUSTOM_VISION_AI/model.onnx_b4_gpu0_fp32.engine
0:00:07.133369029     1     0x3bea4d00 INFO                 nvinfer gstnvinfer.cpp:619:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Info from NvDsInferContextImpl::generateBackendContext() <nvdsinfer_context_impl.cpp:1805> [UID = 1]: Use deserialized engine model: /data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/../../CUSTOM_VISION_AI/model.onnx_b4_gpu0_fp32.engine
0:00:07.325240353     1     0x3bea4d00 INFO                 nvinfer gstnvinfer_impl.cpp:313:notifyLoadModelStatus:<primary_gie> [UID 1]: Load new model:/data/misc/storage/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/services/DEEPSTREAM/configs/config_infer_primary_CustomVisionAI.txt sucessfully
nvds_msgapi_connect : connect success
Opening in BLOCKING MODE
WARNING: [TRT]: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
INFO: [FullDims Engine Info]: layers num: 2
0   INPUT  kFLOAT data            3x416x416       min: 1x3x416x416     opt: 4x3x416x416     Max: 4x3x416x416
1   OUTPUT kFLOAT model_outputs0  45x13x13        min: 0               opt: 0               Max: 0


Runtime commands:
        h: Print this help
        q: Quit

        p: Pause
        r: Resume

NOTE: To expand a source in the 2D tiled display and view object details, left-click on the source.
      To go back to the tiled display, right-click anywhere on the window.

** INFO: <bus_callback:181>: Pipeline ready
```

**Comment by AndreV84** [comment]
@toolboc I put the placeholder
also make sure that there is no GL sink
but the logs still show yesterdays errors not todays errors
how to undeploy/ wipe the whole thing to get the updated todays logs reflected?

**Comment by AndreV84** [comment]
now it shows the status as running in microsoft Azure
but it does also show that there is no deployment configuration [ previously it was listed in deployment cofiguration at azure
previously it would show the entire deployment manifest there
how to wipe then redo correctly?

**Comment by AndreV84** [comment]
it seems that it fails more often if just to use vscode on jetson or vscode on x86_64
but when approaching from two vscodes from both devices it gets step further but still some issues

**Comment by AndreV84** [comment]
```
(deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.124: g_object_get: assertion 'G_IS_OBJECT (object)' failed


(deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.164: g_object_get: assertion 'G_IS_OBJECT (object)' failed

(deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.205: g_object_get: assertion 'G_IS_OBJECT (object)' failed



(deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.245: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Message sent : {
  "version" : "4.0",
  "id" : 7267,
  "@timestamp" : "2021-04-07T18:34:50.178Z",
  "sensorId" : "Camera_0",
  "objects" : [
    "-1|208.269|21.1966|240|54.7009|car"
```
it shows errors like that
is it fine?

**Comment by AndreV84** [comment]
could you extend on how to read events from Azure mqtt interface, please?

**Comment by toolboc** [comment]
> ```
> (deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.124: g_object_get: assertion 'G_IS_OBJECT (object)' failed
> 
> 
> (deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.164: g_object_get: assertion 'G_IS_OBJECT (object)' failed
> 
> (deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.205: g_object_get: assertion 'G_IS_OBJECT (object)' failed
> 
> 
> 
> (deepstream-test5-app:1): GLib-GObject-CRITICAL **: 18:34:50.245: g_object_get: assertion 'G_IS_OBJECT (object)' failed
> Message sent : {
>   "version" : "4.0",
>   "id" : 7267,
>   "@timestamp" : "2021-04-07T18:34:50.178Z",
>   "sensorId" : "Camera_0",
>   "objects" : [
>     "-1|208.269|21.1966|240|54.7009|car"
> ```
> 
> it shows errors like that
> is it fine?

This is fine, closing the issue now as  you seem to be up and running.  Please keep additional questions related to the topic of the original issue going forward.

**Comment by toolboc** [comment]
> could you extend on how to read events from Azure mqtt interface, please?

You can take a look at "Sample test application 5" and the "Azure MQTT test application" that are included in the DeepStream SDK.  Some basic description and the path locations for the source code of these applications can be found in the [DeepStream C/C++  Sample Apps documentation](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_C_Sample_Apps.html).

**Comment by AndreV84** [comment]
@toolboc could you direct on how to add message broker GPS information, please?
given there is GPS uinit connected to the jetson sao we would like the messages to come to Azure from it
