### ISSUE TITLE
Stop auto strat

### ISSUE THREAD

**Issue by joaquin03** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#5]
Hi! Grate tutorial!

How i can stop the auto start function, i want to do some other stuff with my jetson nano, and i can't stop DeepStreamTest5App

Thanks!

**Comment by toolboc** [comment]
You should be able to "stop" the IoT Edge runtime service with:
`sudo service iotedge stop`

Similarly, to restart:
`sudo service iotedge restart`

Cheers!
