### ISSUE TITLE
Resource Not Found Error for Offline Videos as Input

### ISSUE THREAD

**Issue by santle** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#6]
Thanks for the great work!!
Instead of RTSP stream, I used an offline locally stored video as an input.
changed the config. to
type=2
uri=file:///home/test.mp4
Both Yolo3 and CustomVision.ai models couldn't be able to pick up this path and shows "Resource NOT found error"
The same video runs on Resnet10 model of DeepStream samples.
Do I need to add any more changes to the config file to run videos as input.

**Comment by toolboc** [comment]
It sounds like the video file is not accessible to the container.  Have you properly mounted the path to the video file to make it accessible  for playback in the NVIDIADeepStreamSDK module?  The [default configuration bind mounts the `/data/misc/storage` path](https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/blob/master/deployment-iothub/deployment.template.json#L77), you may have luck by referencing the file from within that path or you could add an additional volume mount which points to your current video path by modifying that same linked area of the deployment.template.
