### ISSUE TITLE
Module 4.1 error

### ISSUE THREAD

**Issue by santle** [toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure#7]
Testing with SampleInput / DemoData produces the following error:

 Comparison is not allowed for operands of type 'nvarchar(max)' and 'datetime' in expression 'DeepStreamInput . [@timestamp] ! = CAST ( '1970-01-01T00:00:00.000Z' AS datetime )'.

**Comment by toolboc** [comment]
Thanks for reporting, it looks like this is due to a service side change, I've modified the query to work with the new type expectations.

**Comment by toolboc** [comment]
Please be aware that if you were working with a previous version of the repo and got caught in the middle of this change, you will need to update the DeepStreamAnalytics image URI and the associated `properties.desired` as shown in this commit: https://github.com/toolboc/Intelligent-Video-Analytics-with-NVIDIA-Jetson-and-Microsoft-Azure/commit/f4015cd80827da5e3312c94dd4c3d910975bf713
